export const apologyContent = {
  recipientName: "Pvi",
  senderName: "Aji",

  intro: {
    greeting: "Hey Pvi...",
    line1: "I know you're angry 🥺",
    // line2: "Okay okay...",
    line3: "You asked me to say sorry 50 times.",
    line4: "So I made a solution.",
    button: "Let's do this",
  },

  envelope: {
    title: "Apparently saying sorry once wasn't enough...",
    subtitle:
      "Since you asked for 50 sorries, I have decided to take this request VERY seriously.",
    tease: "Unfortunately for you, I'm also making you count them. 😂",
    button: "Open it",
    letterGreeting: "..... Pvi,",
    letterBody: "Okay... I'm sorry 😭",
    letterNote: "Now don't judge me. I made a whole website for this.",
    continueButton: "Continue to the Sorries",
  },

  apologies: [
    "Sorry for being annoying sometimes",
    "Okay, that one was definitely my fault.",
    "Sorry. No excuses.",
    "Sorry for testing your patience 😇",
    "Sorry for talking too much.",
    "Sorry for not listening immediately 👀",
    "Sorry for being stubborn.",
    "Sorry for making you roll your eyes 😂",
    "Sorry for that silly thing I did.",
    "Sorry for making you mad at me 🥺",
    "Sorry for thinking I was right when I clearly wasn't.",
    "Sorry, you win this round 🏳️",
    "Sorry for being a dramatic clown in so many things..",
    "Sorry for taking your peaceful mood away.",
    "Sorry for running my mouth without thinking first.",
    "Sorry for being 99% trouble and 1% sweet.",
    "Sorry for interrupting you when you were speaking.",
    "Sorry for assuming things like an idiot.",
    "Sorry for having selective hearing sometimes 🙉",
    "Sorry for pushing your buttons on purpose.",
    "Sorry for my terrible jokes at the worst possible time.",
    "Sorry for taking 10 minutes to realize I was wrong.",
    "Sorry for being cute enough to get away with it (wait, sorry 😂)",
    "Sorry for forgetting that you are always right.",
    "Sorry, Pvi. Seriously, For.....",
    "Sorry for acting like I didn't hear you sigh.",
    "Sorry for not ordering snacks before starting an argument.",
    "Sorry for whatever face I made when you were scolding me.",
    "Sorry for being hopelessly clumsy with my words.",
    "Sorry for exhausting your patience bank account.",
    "Sorry for arguing back when I should have just nodded.",
    "Sorry for the unnecessary drama.",
    "Sorry for acting like a 5-year-old child.",
    "Sorry for making your blood pressure go up 📈",
    "Sorry for not bribing you with food immediately.",
    "Sorry for being a walking headache today.",
    "Sorry for not giving you the princess treatment you deserve 👑",
    "Sorry for taking you for granted even for a second.",
    "Sorry for being slow to apologize properly.",
    "Sorry for all the eye-rolls I caused.",
    "Sorry for my lack of common sense sometimes.",
    "Sorry for making you repeat yourself 3 times.",
    "Sorry for being so hard-headed.",
    "Sorry for being the most annoying person you know.",
    "Sorry for disturbing your peace of mind.",
    "Sorry for not realizing sooner how much I upset you.",
    "Sorry for being completely hopeless without your smile.",
    "Sorry for every second you spent being annoyed at me.",
    "Sorry for the 49 times before this.",
    "50. FIFTY. Official quota fulfilled! 🥳",
  ],

  milestones: {
    5: "Five already. I'm fully committed now.",
    10: "Ten. This is getting serious.",
    15: "Fifteen down. My thumbs are warming up.",
    20: "Twenty. I hope you're keeping count 👀",
    25: "HALFWAY! Look at the dedication.",
    30: "Thirty. I definitely didn't think this through 😂",
    40: "Forty. Almost there, don't give up on me!",
    45: "Forty-five. Just five more to go.",
    49: "One more. The final stretch.",
    50: "50 OFFICIAL SORRIES DELIVERED.",
  } as Record<number, string>,

  bonusSorry: {
    preamble: "But wait...",
    prompt: "I think I owe you one more.",
    button: "One last sorry",
    message: "Sorry, Pvi.",
    subtext: "That one was actually from my heart.",
  },

  finalCard: {
    title: "Pvi...",
    heading: "Sorry.",
    p1: "I know I could have just texted a boring apology.",
    p2: "But where's the fun in that?",
    p3: "Now I've officially said sorry 50 times. Plus one extra.",
    p4: "Now give me that cute smile and stop being angry 😂",
    signoff: "— Aji",
    endTease: "Okay, I'm done. Your message is on its way to Aji ❤️",
  },
};
