export const apologyContent = {
  recipientName: "Pvi",
  senderName: "Aji",

  intro: {
    greeting: "Hey Pvi...",
    line1: "I know you're angry 🥺",
    line3: "You asked me to say sorry 50 times.",
    line4: "So I made a solution.",
    button: "Let's do this",
  },

  envelope: {
    title: "Apparently saying sorry once wasn't enough...",
    subtitle:
      "Since you asked for 50 sorries, I have decided to take this request VERY seriously.",
    tease: "Unfortunately for you, I'm also making you count them. 😂",
    button: "Open it",
    letterGreeting: "..... Pvi,",
    letterBody: "I'm sorry 😕",
    letterNote: "Now don't judge me. I made a whole website for this.",
    continueButton: "Continue ❤️",
  },

  apologies: [
    "Sorry for made you cry..❣",
    "Okay, that one was definitely my fault.",
    "Sorry. No excuses.",
    "Sorry for testing your patience 😇",
    "Sorry for talking too much.",
    "Sorry for not listening immediately 👀",
    "Sorry for being stubborn.",
    "Sorry for making you roll your eyes ❣",
    "Sorry for that silly thing I did.",
    "Sorry for making you mad at me 🥺",
    "Sorry for thinking I was right when I clearly wasn't.",
    "Sorry, you win this round 🏳️",
    "Sorry for being a dramatic clown in so many things..",
    "Sorry for taking your peaceful mood away.",
    "Sorry for getting angry without thinking first.",
    "Sorry for being 1% trouble and 99% sweet 🤭.",
    "Sorry for interrupting you when you were speaking.",
    "Sorry for assuming things like an idiot.",
    "Sorry for having selective hearing sometimes 🙉",
    "Sorry for pushing your buttons on purpose.",
    "Sorry for my terrible jokes at the worst possible time.",
    "Sorry for taking 10 minutes to realize I was wrong.",
    "Sorry for being cute enough to get away with it (wait, sorry 😂)",
    "Sorry for forgetting that you are always right.",
    "Sorry, Pvi. Seriously, For.....",
    "Sorry for acting like I didn't hear you sigh.",
    "Sorry for not ordering snacks before starting an argument.",
    "Sorry for whatever face I made when you were scolding me.",
    "Sorry for being hopelessly clumsy with my words.",
    "Sorry for exhausting your patience bank account.",
    "Sorry for not arguing back when you shouted.",
    "Sorry for the being late in some things...",
    "Sorry for acting like a 21-year-old child.",
    "Sorry for making your blood pressure go up 📈",
    "Sorry for not bribing you with food immediately.",
    "Sorry for being a walking headache yesterday.",
    "Sorry for Lokesh issue.....",
    "Sorry for taking you for granted even for a second.",
    "Sorry for being slow to apologize properly.",
    "Sorry for all the eye-rolls I caused.",
    "Sorry for my lack of common sense sometimes.",
    "Sorry for making you repeat yourself 3 times.",
    "Sorry for being so hard-headed sometimes.",
    "Sorry for being the most annoying person sometimes.",
    "Sorry for disturbing your peace of mind.",
    "Sorry for not realizing sooner how much I upset sometimes.",
    "Sorry for being completely hopeless without your smile.❣",
    "Sorry for every second you spent being annoyed at me.",
    "Sorry for the 49 times before this.",
    "50. FIFTY. Officialy fulfilled! 🥳",
  ],

  milestones: {
    5: "Five already. I'm fully committed now.",
    10: "Ten. This is getting serious.",
    15: "Fifteen down. My thumbs are warming up.",
    20: "Twenty. I hope you're keeping count 👀",
    25: "HALFWAY! Look at the dedication.",
    30: "Thirty. I definitely didn't think this through 😂",
    40: "Forty. Almost there, don't give up on me!",
    45: "Forty-five. Just five more to go.",
    49: "One more. The final stretch.",
    50: "50 OFFICIAL SORRIES DELIVERED.",
  } as Record<number, string>,

  bonusSorry: {
    preamble: "But wait...",
    prompt: "I think I owe you one more.",
    button: "One last sorry",
    message: "Sorry, Pvi.",
    subtext: "That one was actually from my heart.",
  },

  finalCard: {
    title: "Pvi...",
    heading: "Sorry.",
    p1: "Hope you fogive me.",
    p2: "But I a'm still angry at you for ... ........ ..❤️",
    p3: "Now I've officially said sorry 50 times.",
    p4: "Want to tell you something...",
    lyrics: `Ellora sirpangal un meedhu kaadhalurum
Uyire illaadha kal kooda kaamamurum
Un meedhu kaadhal konda
Maanudan thaan enna aaguvaan`,
    signoff: "— Aji",
    endTease: "Okay, I'm done. Your message is on its way to Aji ❤️",
  },
};
